### PR TITLE
Fixes #87 and ensures that user agents are only added once per unique string.

### LINKED ISSUE #87: User agents are applied multiple times
**Describe the bug**
User agent strings are applied multiple times because the addOption keeps applying them on subsequent queries.

**To Reproduce**
Steps to reproduce the behavior including calling code:
1. Run the db:backup:list command using Acquia Cli
2. Dump the user agent headers
3. See a string containing multiple instances of each user agent

**Expected behavior**
A single user agent string for each library in use.

### PR DESCRIPTION
**Pull request by typhonius**

### CODE REVIEW

File: src/Connector/Client.php [hunk 1]
```diff
@@ -203,4 +210,20 @@ public function addOption($name, $value): void
     {
         $this->options = array_merge_recursive($this->options, [$name => $value]);
     }
+
+    /**
+     * @inheritdoc
+     */
+    public function setUserAgent($name): void
```
Comment (typhonius) [inline src/Connector/Client.php:217]: We may need to change this so the ordering is based on when this method is called. Currently it is alphabetical but we could use a numerical array and just add the value.

Comment (typhonius) [reply src/Connector/Client.php:217]: Reminder to add another user agent in tests on the other side alphabetically to ensure the right order is attained.

**Review by korkhau — APPROVED** [review]
